In [1]:
import numpy as np

In [2]:
first_array = np.array([1,3,5,7])
second_array = np.array([2,4,6,8])

In [3]:
np.add(first_array, second_array)

array([ 3,  7, 11, 15])

In [4]:
np.multiply = (first_array, second_array)

In [5]:
np.multiply

(array([1, 3, 5, 7]), array([2, 4, 6, 8]))

In [6]:
numbers = np.array([1.2334, 2.3456, 3.6783, 5.7532])

np.round(numbers,2)

array([1.23, 2.35, 3.68, 5.75])

In [7]:
grades = np.array([76,84,24,79,11])

In [8]:
np.mean(grades)

54.8

In [9]:
array1= np.array([[1,3],
                 [5,6]])